language: node_js
node_js:
 - "node"

branches:
 only:
   - master
   - /^greenkeeper/.*$/

jobs:
  include:
    - stage: lint
      node_js: lts/*
      script: npm run lint

    - stage: test with mongoose v4.x
      node_js: lts/*
      script: npm run test:v4

    - stage: test with mongoose v5.x
      node_js: lts/*
      script: npm run test:v5

    - stage: test mongoose latest
      node_js: lts/*
      script: npm run test

    - stage: coverage
      node_js: 9
      script: npm run cover
