language: node_js
node_js:
 - "node"

branches:
 only:
   - master
   - /^greenkeeper/.*$/

jobs:
  include:
    - stage: lint
      node_js: lts/*
      script: npm run lint

    - stage: test_v4
      node_js: lts/*
      script: npm run test:v4

    - stage: test_v5
      node_js: lts/*
      script: npm run test:v5

    - stage: test_latest
      node_js: lts/*
      script: npm run test

    - stage: coverage
      node_js: 9
      script: npm run cover
